schemaVersion: 2.2.0
metadata:
  name: spring-boot-java21
  version: 1.0.0
  displayName: Spring Boot Java 21 Application
  description: Spring Boot batch application with Java 21

components:
  # メインの開発コンテナ（Java 21 + Maven）
  - name: tools
    container:
      image: eclipse-temurin:21-jdk
      memoryLimit: 2Gi
      memoryRequest: 1Gi
      cpuLimit: 2000m
      cpuRequest: 1000m
      mountSources: true
      volumeMounts:
        - name: m2
          path: /home/user/.m2
      env:
        - name: JAVA_HOME
          value: /opt/java/openjdk
        - name: MAVEN_OPTS
          value: -Xmx1024m
      endpoints:
        - name: spring-boot
          targetPort: 8080
          exposure: public
          protocol: http
        - name: debug
          targetPort: 5005
          exposure: internal
          protocol: tcp

  # PostgreSQLデータベース
  - name: postgres
    container:
      image: postgres:15-alpine
      memoryLimit: 512Mi
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: migration_db
      endpoints:
        - name: postgres
          targetPort: 5432
          exposure: internal

  # Mavenローカルリポジトリ用のボリューム
  - name: m2
    volume:
      size: 3Gi

commands:
  # 依存関係のダウンロード
  - id: maven-download-dependencies
    exec:
      component: tools
      commandLine: mvn dependency:resolve dependency:resolve-plugins
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: build
        isDefault: false

  # アプリケーションのビルド
  - id: maven-build
    exec:
      component: tools
      commandLine: mvn clean package -DskipTests
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: build
        isDefault: true

  # テスト実行
  - id: maven-test
    exec:
      component: tools
      commandLine: mvn test
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: test
        isDefault: true

  # Spring Bootアプリケーションの起動
  - id: spring-boot-run
    exec:
      component: tools
      commandLine: mvn spring-boot:run
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: run
        isDefault: true

  # デバッグモードで起動
  - id: spring-boot-debug
    exec:
      component: tools
      commandLine: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: debug
        isDefault: true

  # jarファイルから起動
  - id: run-jar
    exec:
      component: tools
      commandLine: java -jar target/data-migration-batch-1.0.0.jar
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: run
        isDefault: false

  # クリーン
  - id: maven-clean
    exec:
      component: tools
      commandLine: mvn clean
      workingDir: ${PROJECT_SOURCE}

events:
  # ワークスペース起動時に依存関係をダウンロード
  postStart:
    - maven-download-dependencies
