schemaVersion: 2.2.2
metadata:
  name: ikou-springboot
  displayName: Spring Boot + Postgres (Dev Spaces)
  description: Spring Boot app with PostgreSQL running in the same workspace Pod
  projectType: springboot
  language: Java
  version: 1.0.0
  globalMemoryLimit: 2674Mi

components:
  - name: tools
    container:
      image: registry.access.redhat.com/ubi9/openjdk-21
      command: ["tail", "-f", "/dev/null"]
      memoryLimit: 1024Mi
      mountSources: true
      endpoints:
        - name: https-app
          targetPort: 8080
          protocol: https
        - name: debug
          targetPort: 5858
          exposure: none
      volumeMounts:
        - name: m2
          path: /home/user/.m2
      env:
        - name: DEBUG_PORT
          value: "5858"
        # DBは同一Podなので localhost にする
        - name: DB_URL
          value: "jdbc:postgresql://localhost:5432/migration_db"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"

  - name: m2
    volume:
      size: 3Gi

  # Postgres container (same Pod)
  - name: postgres
    container:
      image: postgres:16
      memoryLimit: 768Mi
      endpoints:
        - name: postgres
          targetPort: 5432
          exposure: none
      env:
        - name: POSTGRES_DB
          value: "migration_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"

commands:
  - id: build
    exec:
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: mvn -Dmaven.repo.local=/home/user/.m2/repository clean package -Dmaven.test.skip=true

  - id: run
    exec:
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: mvn -Dmaven.repo.local=/home/user/.m2/repository spring-boot:run

  - id: debug
    exec:
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=${DEBUG_PORT},suspend=n -jar target/*.jar
